Twilo/force-app/main/default/objects/TwilloConfig__c/TwilloConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Twillo Config</label>
</CustomObject>

Twilo/force-app/main/default/objects/TwilloConfig__c/fields/accountSid__c.field-meta.xml
<CustomField>
    <fullName>accountSid__c</fullName>
    <label>account Sid</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Twilo/force-app/main/default/classes/SmsMockHttpGeneratorTest.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 01-20-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
global with sharing class SmsMockHttpGeneratorTest implements HttpCalloutMock{

    Integer statusCode =  201;
    global SmsMockHttpGeneratorTest() {
    }

    global SmsMockHttpGeneratorTest(Integer statusCode) {
        this.statusCode = statusCode;
    }
    global HTTPResponse respond(HTTPRequest req) {
        TwilloConfig__c twilloConfiguration = TwilloConfig__c.getOrgDefaults();

        // Optionally, only send a mock response for a specific endpoint
        // and method.
        String accountSid = twilloConfiguration?.accountSid__c; // you can put ACCOUNT SID from twilio account
        System.assertEquals('https://api.twilio.com/2010-04-01/Accounts/'+accountSid+'/SMS/Messages.json', req.getEndpoint());
        System.assertEquals('POST', req.getMethod());
        
        // Create a fake response
        HttpResponse res = new HttpResponse();
        res.setHeader('Content-Type', 'application/json');
        res.setBody('{"errorMessage":"Sms Sent Failed"}');
        res.setStatusCode(statusCode);
        return res;
    }

   

}