Twilo/force-app/main/default/objects/Account/fields/customer_Classification__c.field-meta.xml
<CustomField>
    <fullName>customer_Classification__c</fullName>
    <description>customer classification formula field</description>
    <formula>IF(customerSpendSummary__c &gt;=  $Setup.CustomClassification__c.goldCustomerValue__c , &apos;GOLD&apos;,
 IF(customerSpendSummary__c &gt;=  $Setup.CustomClassification__c.silverCustomerValue__c , &apos;SILVER&apos;,
IF(customerSpendSummary__c &gt;=  $Setup.CustomClassification__c.bronzeCustomerValue__c , &apos;BRONZE&apos;, &apos;&apos;)))</formula>
    <label>Customer Classification</label>
    <type>Text</type>
</CustomField>

Twilo/force-app/main/default/objects/Account/fields/customerSpendSummary__c.field-meta.xml
<CustomField>
    <fullName>customerSpendSummary__c</fullName>
    <description>total spend of all closed opportunity for the customer</description>
    <label>Customer Spend Summary</label>
    <summarizedField>Opportunity.Amount</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>Closed Won</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Twilo/force-app/main/default/objects/CustomClassification__c/CustomClassification__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom Setting to set gold , silver ,bronze customer value</description>
    <label>Custom Classification</label>
</CustomObject>

Twilo/force-app/main/default/objects/CustomClassification__c/fields/bronzeCustomerValue__c.field-meta.xml
<CustomField>
    <fullName>bronzeCustomerValue__c</fullName>
    <label>bronzeCustomerValue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Twilo/force-app/main/default/objects/CustomClassification__c/fields/goldCustomerValue__c.field-meta.xml
<CustomField>
    <fullName>goldCustomerValue__c</fullName>
    <label>goldCustomerValue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Twilo/force-app/main/default/objects/CustomClassification__c/fields/silverCustomerValue__c.field-meta.xml
<CustomField>
    <fullName>silverCustomerValue__c</fullName>
    <label>silverCustomerValue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Twilo/force-app/main/default/objects/TriggerConfig__c/fields/isAccountTriggerEnabled__c.field-meta.xml
<CustomField>
    <fullName>isAccountTriggerEnabled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isAccountTriggerEnabled</label>
    <type>Checkbox</type>
</CustomField>

Twilo/force-app/main/default/classes/AccountHandlerTest.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 01-17-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/

@isTest
private class AccountHandlerTest {
    private static Integer oppCounter = 0;
    @TestSetup
    static void makeData()
    {
        configureClassificationSetting();
        disableAccountTrigger();
        Account testAccount = new Account(name ='testAccount');
        insert testAccount;
    }

    @isTest
    static void testAccountFormulaField(){
        Account testAccount = [select id, name, customer_Classification__c, customerSpendSummary__c FROM Account LIMIT 1 ];

        System.assertEquals(testAccount.customer_Classification__c, null, 'customer default classification is to be empty');
        Opportunity goldOpportunity = createOpportunity(System.Label.goldCustomerLabel, testAccount.Id);
        insert goldOpportunity;
        testAccount = [select id, name, customer_Classification__c, customerSpendSummary__c FROM Account where Id = :testAccount.Id LIMIT 1 ];
        System.assertEquals( System.Label.goldCustomerLabel, testAccount.customer_Classification__c, 'customer classification has to be Gold');
  
        emptyOpportunity(testAccount.Id);
        Opportunity silverOpportunity = createOpportunity(System.Label.silverCustomerLabel, testAccount.Id);
        insert silverOpportunity;
        testAccount = [select id, name, customer_Classification__c, customerSpendSummary__c FROM Account LIMIT 1 ];
        System.assertEquals(System.Label.silverCustomerLabel, testAccount.customer_Classification__c,  'customer classification has to be Silver');
        
        emptyOpportunity(testAccount.Id);
        Opportunity bronzeOpportunity = createOpportunity(System.Label.bronzeCustomerLabel, testAccount.Id);
        insert bronzeOpportunity;
        testAccount = [select id, name, customer_Classification__c, customerSpendSummary__c FROM Account LIMIT 1 ];
        System.assertEquals(System.Label.bronzeCustomerLabel, testAccount.customer_Classification__c,  'customer classification has to be Bronze');
	}

    @isTest
    static void testAccountGoldTierEvent() {
        enableAccountTrigger();
        Account testAccount = [select id, name, customer_Classification__c, customerSpendSummary__c FROM Account LIMIT 1 ];
        Opportunity bronzeOpportunity = createOpportunity(System.Label.bronzeCustomerLabel, testAccount.Id);
        insert bronzeOpportunity;
        Opportunity goldOpportunity = createOpportunity(System.Label.goldCustomerLabel, testAccount.Id);
        insert goldOpportunity;
        //email is sent mock service
    }

    @isTest
    static void filterGoldAccountsChange() {
        List<Account> changedGoldAccounts;
        Account testAccount = [select id, name, customer_Classification__c, customerSpendSummary__c FROM Account LIMIT 1 ];
        Opportunity bronzeOpportunity = createOpportunity(System.Label.bronzeCustomerLabel, testAccount.Id);
        insert bronzeOpportunity;
        testAccount = [select id, name, customer_Classification__c, customerSpendSummary__c FROM Account LIMIT 1 ];
        Map<Id, Account>  oldAccountMap = new Map<Id, Account>();
        oldAccountMap.put(testAccount.Id, testAccount);

        Opportunity goldOpportunity = createOpportunity(System.Label.goldCustomerLabel, testAccount.Id);
        insert goldOpportunity;
        testAccount = [select id, name, customer_Classification__c, customerSpendSummary__c FROM Account LIMIT 1 ];
        Map<Id, Account>  newAccountMap = new Map<Id, Account>();
        newAccountMap.put(testAccount.Id, testAccount);

        changedGoldAccounts = AccountHandler.filterGoldAccountsChange(oldAccountMap, newAccountMap);
        System.assertEquals(changedGoldAccounts.size(), 1, 'One of the account has been converted to gold');

    }
    private static void emptyOpportunity(Id accountId) {
        List<Opportunity> opportunities = [select id from Opportunity where AccountId = :accountId];
        if(!opportunities.isEmpty()) {
            delete opportunities;
        }
    }
    

    private static Opportunity createOpportunity(String type, Id accountId) {
        CustomClassification__c setting = CustomClassification__c.getOrgDefaults();
        Opportunity newOpportunity = new Opportunity(name = 'opp'+oppCounter, accountId = accountId, CloseDate = System.today(), StageName='Closed Won');
        oppCounter++;
        if(type == System.Label.goldCustomerLabel) {
            newOpportunity.amount = setting.goldCustomerValue__c;
        } else if(type == System.Label.silverCustomerLabel) {
            newOpportunity.amount = setting.silverCustomerValue__c;

        }
        else if(type == System.Label.bronzeCustomerLabel) {
            newOpportunity.amount = setting.bronzeCustomerValue__c;
        } else {
            newOpportunity.amount = setting.bronzeCustomerValue__c - 1;
        }
        return newOpportunity;
    }
 
    private static void configureClassificationSetting() {
        CustomClassification__c setting = new CustomClassification__c(SetupOwnerId=UserInfo.getOrganizationId());
        setting.bronzeCustomerValue__c = 10000;
        setting.silverCustomerValue__c = 25000;
        setting.goldCustomerValue__c = 50000;
        upsert setting;
    }

    private static void disableAccountTrigger() {
        TriggerConfig__c setting = new TriggerConfig__c(SetupOwnerId=UserInfo.getOrganizationId());
        setting.isAccountTriggerEnabled__c = false;
        upsert setting;
    }

    private static void enableAccountTrigger() {
        TriggerConfig__c setting = TriggerConfig__c.getOrgDefaults();
        setting.isAccountTriggerEnabled__c = true;
        upsert setting;
    }
}