Twilo/force-app/main/default/objects/Account/fields/customer_Classification__c.field-meta.xml
<CustomField>
    <fullName>customer_Classification__c</fullName>
    <description>customer classification formula field</description>
    <formula>IF(customerSpendSummary__c &gt;=  $Setup.CustomClassification__c.goldCustomerValue__c , &apos;GOLD&apos;,
 IF(customerSpendSummary__c &gt;=  $Setup.CustomClassification__c.silverCustomerValue__c , &apos;SILVER&apos;,
IF(customerSpendSummary__c &gt;=  $Setup.CustomClassification__c.bronzeCustomerValue__c , &apos;BRONZE&apos;, &apos;&apos;)))</formula>
    <label>Customer Classification</label>
    <type>Text</type>
</CustomField>

Twilo/force-app/main/default/objects/Account/fields/customerSpendSummary__c.field-meta.xml
<CustomField>
    <fullName>customerSpendSummary__c</fullName>
    <description>total spend of all closed opportunity for the customer</description>
    <label>Customer Spend Summary</label>
    <summarizedField>Opportunity.Amount</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>Closed Won</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Twilo/force-app/main/default/objects/CustomClassification__c/CustomClassification__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom Setting to set gold , silver ,bronze customer value</description>
    <label>Custom Classification</label>
</CustomObject>

Twilo/force-app/main/default/objects/CustomClassification__c/fields/goldCustomerValue__c.field-meta.xml
<CustomField>
    <fullName>goldCustomerValue__c</fullName>
    <label>goldCustomerValue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Twilo/force-app/main/default/classes/AccountHandler.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 01-17-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class AccountHandler {

    private static CustomClassification__c customerclassification = CustomClassification__c.getOrgDefaults();



    public static void processAccountsUpdate(List<Account> accountsList, 
                                    Map<Id, Account> accountOldMap, Map<Id, Account> accountNewMap) 
    {
        List<Account> changedGoldAccounts = filterGoldAccountsChange(accountOldMap, accountNewMap );
    }

    public static List<Account> filterGoldAccountsChange( Map<Id, Account> accountOldMap, Map<Id, Account> accountNewMap)
    {
        List<Account> changedGoldAccounts = new List<Account>();
        for (Id accountId : accountOldMap.keySet()) {
            if(isAccountSpendSummaryGotGold(accountOldMap.get(accountId), accountNewMap.get(accountId))) {
                changedGoldAccounts.add(new Account(Id = accountId));
            }
        }
        return changedGoldAccounts;
    }

    private static boolean isAccountSpendSummaryGotGold(Account oldAccount, Account newAccount) {
        /*
        if(oldAccount.customer_Classification__c != 'Gold' && 
                (oldAccount?.customerSpendSummary__c != newAccount?.customerSpendSummary__c)
                 && newAccount?.customerSpendSummary__c >= customerclassification?.goldCustomerValue__c) {
            return true;
        }
        return false; */
        if(oldAccount.customer_Classification__c != newAccount.customer_Classification__c && 
        newAccount.customer_Classification__c == 'Gold') {
            return true;
        }
        return false;

    }

}